### ISSUE TITLE
Lexeme Details: Component Of

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/data-explorer#369]
Add a "Component Of" field to the Form Details within the Lexeme Details page.

# To Do

- [x] design data format
  ```yml
  componentOf:
    id:    {UUID}
    lemma: {lemma}
  ```
- [x] design UI
  - This will look exactly like the Cross References field. 
- [x] add sample data
- [x] add HTML
- [x] add CSS
- [x] add integration tests
